import type { Metadata } from "next";
import { Open_Sans, Montserrat, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { createTheme, ThemeProvider } from "flowbite-react";

const customTheme = createTheme({
  button: {
    color: {
      primary: "bg-black/70",
    },
  },
  megaMenu: {
    root: { base: "bg-black/70" },
  },
});

const open_sans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${open_sans.variable} ${montserrat.variable} h-[2000px]`}
    >
      <ThemeProvider theme={customTheme}>
        <body className="antialiased bg-amber-50">
          <Header />
          <>{children}</>
        </body>
      </ThemeProvider>
    </html>
  );
}
